name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Debug workspace layout
      - name: Debug workspace
        run: |
          echo "=== WORKSPACE PWD ==="
          pwd
          echo "--- WORKSPACE CONTENTS ---"
          ls -R .
          echo "=== deploy.yml CONTENTS ==="
          sed -n '1,50p' .github/workflows/deploy.yml

      # 3. Raw FTP handshake test
      - name: Test raw FTP connection
        env:
          HOST: ${{ secrets.FTP_HOST }}
          USER: ${{ secrets.FTP_USER }}
          PASS: ${{ secrets.FTP_PASS }}
        run: |
          apt-get update -qq && apt-get install -y ftp
          ftp -inv $HOST <<EOF
          user $USER $PASS
          pwd
          ls
          quit
          EOF

      # 4. Echo the server-dir secret you’ve set
      - name: Debug server-dir value
        run: |
          echo ">>> server-dir from secret FTP_SERVER_DIR is: '${{ secrets.FTP_SERVER_DIR }}'"

      # 5. Actual FTP deploy action
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server:      ${{ secrets.FTP_HOST }}
          username:    ${{ secrets.FTP_USER }}
          password:    ${{ secrets.FTP_PASS }}
          protocol:    ftp
          port:        21
          local-dir:   "./"
          server-dir:  ${{ secrets.FTP_SERVER_DIR }}   # adjust this based on raw FTP test
          exclude: |
            .github/**
            wp-config.php
            .gitignore
