name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Install lftp
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      # 3. Mirror via lftp
      - name: Mirror files to InfinityFree
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          echo "Starting lftp mirror to $FTP_HOST:/htdocs"
          lftp -u "$FTP_USER","$FTP_PASS" "$FTP_HOST" <<EOF
            set ftp:ssl-allow no
            mirror -R \
              --delete \
              --verbose \
              --parallel=2 \
              ./   /htdocs
            quit
          EOF
