name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Mirror files to InfinityFree
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          echo "Starting lftp mirror to $FTP_HOST:/htdocs (no perms)"
          lftp -u "$FTP_USER","$FTP_PASS" "$FTP_HOST" <<EOF
            set ftp:ssl-allow no
            set ftp:preserve-permissions false
            mirror -R \
              --delete \
              --verbose \
              --parallel=2 \
              --exclude-glob wp-content.zip \
              ./   /htdocs
            quit
          EOF
